"""Add roles and permissions to User model

Revision ID: 0ce652307cd5
Revises: 2f656ce5acb8
Create Date: 2025-07-05 21:41:12.246257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce652307cd5'
down_revision: Union[str, Sequence[str], None] = '2f656ce5acb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('permissions', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
